export default {
  DELETE_TODO: 'DELETE_TODO',
  INSERT_TODO: 'INSERT_TODO',
  TOGGLE_TODO: 'TOGGLE_TODO',
  TOGGLE_ALL: 'TOGGLE_ALL',
  SET_FILTER: 'SET_FILTER',
  FETCH_POSTS: 'FETCH_POSTS',
  FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
  FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',
}
